.PHONY: clean

clean:
	rm -vf Transfers_MDM1.vs
	rm -vf Transfers_MDM2.vs
	rm -vf Transfers_AM.vs
	rm -vf Transfers_TM.vs
	rm -vf Transfers_NM.vs
	rm -vf Vehicle_Schedules_MDM1.vs
	rm -vf Vehicle_Schedules_MDM2.vs
	rm -vf Vehicle_Schedules_AM.vs
	rm -vf Vehicle_Schedules_TM.vs
	rm -vf Vehicle_Schedules_NM.vs
	rm -vf Canal_Network.vs
	rm -vf Vehicle_Flow.vs
